server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      enable: true
      server:
        git:
          uri: "https://github.com/CamiloLagos/Service-Config"
          searchPaths: config-data


